package chapter08.item50.examples;

import java.io.IOException;
import java.io.InvalidObjectException;
import java.io.ObjectInputStream;
import java.util.Date;

public class Period3 {
	private final Date start;
	private final Date end;

	/**
	 * @param start the beginning of the period
	 * @param end   the end of the period; must not precede start
	 * @throws IllegalArgumentException if start is after end
	 * @throws NullPointerException     if start or end is null
	 */

	// Repaired constructor - makes defensive copies of parameters
	public Period3(Date start, Date end) {
		this.start = start();
		this.end = end();
		if (this.start.compareTo(this.end) > 0)
			throw new IllegalArgumentException(this.start + " after " + this.end);
	}

	// Repaired accessors - make defensive copies of internal fields
	// With the new constructor and the new accessors in place, Period is truly
	// immutable.
	public Date start() {
		return new Date(start.getTime());
	}

	public Date end() {
		return new Date(end.getTime());
	}

	// Loosely speaking, readObject is a constructor that takes a byte stream as its
	// sole parameter. In normal use, the byte stream is generated by serializing a
	// normally constructed instance. The problem arises when readObject is
	// presented with a byte stream that is artificially constructed to generate an
	// object that violates the invariants of its class. Such a byte stream can be
	// used to create an impossible object, which could not have been created using
	// a normal constructor.
	
	// readObject method with validity checking - insufficient!
	private void readObject(ObjectInputStream s) throws IOException, ClassNotFoundException {
		s.defaultReadObject();

		// Check that our invariants are satisfied
		if (start.compareTo(end) > 0)
			throw new InvalidObjectException(start + " after " + end);
	}
}
